apiVersion: v1
kind: Service

metadata:
  name: tech-challenge-2-service

spec:
  type: ClusterIP

  selector:
    app: tech-challenge-2-app

  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      